[THIRDCOAST.WHEEL]
  driveSetpointMax = 5000

[[TALON]]
  name = "azimuth"
  talonIds = [0, 1, 2, 3]
  [TALON.selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
  [TALON.currentLimit]
    continuous = 10
    peak = 0
    peakDuration = 0
  [TALON.motionMagic]
    acceleration = 10_000
    cruiseVelocity = 800
  [[TALON.closedLoopProfile]] # slot 0 MotionMagic, normal
    pGain = 10.0
    iGain = 0.0
    dGain = 100.0
    fGain = 1.0
    iZone = 0
    allowableClosedLoopError = 0
  [[TALON.closedLoopProfile]] # slot 1 MotionMagic, hot
    pGain = 15.0
    iGain = 0.0
    dGain = 150.0
    fGain = 1.0
    iZone = 0
    allowableClosedLoopError = 0
  [[TALON.closedLoopProfile]] # slot 2 MotionMagic, slow
    pGain = 2.5
    iGain = 0.0
    dGain = 25.0
    fGain = 1.0
    iZone = 0
    allowableClosedLoopError = 0

[[TALON]]
 name = "drive"
 talonIds = [10, 11, 12, 13]
 [TALON.selectedFeedbackSensor]
   feedbackDevice = "CTRE_MagEncoder_Relative"
 [TALON.currentLimit]
   continuous = 40
   peak = 0
   peakDuration = 0
 [[TALON.closedLoopProfile]] # slot 0 Velocity
   pGain = 0.1
   iGain = 0.0
   dGain = 1.0
   fGain = 0.03
   iZone = 0
   allowableClosedLoopError = 0